name: appinnovaro
description: forças de venda
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-437.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.2.1
  pdf: ^3.10.8
  barcode: ^2.2.6
  open_file: ^3.2.2
  build_runner: ^2.4.1
  connectivity_plus: ^4.0.1
  loading_animation_widget: ^1.2.0+4
  flutter_typeahead: ^4.7.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^17.1.0
  another_flushbar: ^1.12.30
  flutter_native_splash: ^2.3.2
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0
  provider: ^6.0.5
  consumer: ^2.3.1
  flutter_modular: ^6.3.2
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  device_info_plus: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  restart_app: ^1.2.1
  pagination_flutter: ^0.0.8
  dio: ^5.4.3+1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#F6A200"
  adaptive_icon_foreground: "assets/images/AppIcon.png"
  web:
    generate: false
  image_path: "assets/images/AppIcon.png"

flutter_native_splash:
  color: "#fdfdfd"
  image: assets/images/LogoReduzidaAmarelo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#fdfdfd"
    icon_background_color: "#fdfdfd"
    image: assets/images/LogoReduzidaAmarelo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/user.png
    - assets/images/icons/
    - assets/images/AppIcon.png
    - assets/images/LogoReduzidaAmarelo.png
    - assets/images/icons/barcode.png
    - assets/images/placeholderItem.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/images/on_boarding_images/
    - assets/images/logoFortesLogin.png
    - assets/images/LogoReduzidaFortes.png
fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
